Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t1.micro
    AllowedValues:
    - t1.micro
    - m1.small
    - m1.medium
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  InstanceCount:
    Description: Number of EC2 instances to launch
    Type: Number
    Default: '1'
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: '64'
    m1.small:
      Arch: '64'
    m1.medium:
      Arch: '64'
    t2.micro:
      Arch: '64'
    t2.small:
      Arch: '64'
    t2.medium:
      Arch: '64'
    t2.large:
      Arch: '64'
  AWSRegionArch2AMI:
    us-east-1:
      '32': ami-aba768c2
      '64': ami-02f664ededb0d5286
    us-west-1:
      '32': ami-458fd300
      '64': ami-b18ed2f4
    us-west-2:
      '32': ami-fcff72cc
      '64': ami-feff72ce
    eu-west-1:
      '32': ami-018bb975
      '64': ami-998bb9ed
    sa-east-1:
      '32': ami-a039e6bd
      '64': ami-a239e6bf
    ap-southeast-1:
      '32': ami-425a2010
      '64': ami-5e5a200c
    ap-southeast-2:
      '32': ami-f98512c3
      '64': ami-43851279
    ap-northeast-1:
      '32': ami-7871c579
      '64': ami-7671c577
Resources:
 HandyProBastionInstance:
  Type: AWS::EC2::Instance
  Properties:
   InstanceType: !Ref InstanceType
   KeyName: Training
   ImageId:
    Fn::FindInMap:
     - AWSRegionArch2AMI
     - Ref: AWS::Region
     - Fn::FindInMap:
       - AWSInstanceType2Arch
       - Ref: InstanceType
       - Arch
   NetworkInterfaces:
    - AssociatePublicIpAddress: 'true'
      DeviceIndex: "0"
      GroupSet:
       - !ImportValue SecurityGroupSSH
       - !ImportValue SecurityGroupHTTP
       - !ImportValue SecurityGroupHTTPs
      SubnetId: !ImportValue PublicSunbettoConnect
   Tags:
    - Key: Name
      Value: HandyProBastionServer
    - Key: Project
      Value: HandyPro